chess_gazebo_setup:
  ros__parameters:

    # Black pawns: 201–208 → A7–H7
    black_pawn_201: "A7"
    black_pawn_202: "B7"
    black_pawn_203: "C7"
    black_pawn_204: "D7"
    black_pawn_205: "E7"
    black_pawn_206: "F7"
    black_pawn_207: "G7"
    black_pawn_208: "H7"

    # Black rooks: 209, 210 → A8, H8
    black_rook_209: "A8"
    black_rook_210: "H8"

    # Black knights: 211, 212 → B8, G8
    black_knight_211: "B8"
    black_knight_212: "G8"

    # Black bishops: 213, 214 → C8, F8
    black_bishop_213: "C8"
    black_bishop_214: "F8"

    # Black queen: 215 → D8
    black_queen_215: "D8"

    # Black king: 216 → E8
    black_king_216: "E8"

    # White pawns: 301–308 → A2–H2
    white_pawn_301: "A2"
    white_pawn_302: "B2"
    white_pawn_303: "C2"
    white_pawn_304: "D2"
    white_pawn_305: "E2"
    white_pawn_306: "F2"
    white_pawn_307: "G2"
    white_pawn_308: "H2"

    # White rooks: 309, 310 → A1, H1
    white_rook_309: "A1"
    white_rook_310: "H1"

    # White knights: 311, 312 → B1, G1
    white_knight_311: "B1"
    white_knight_312: "G1"

    # White bishops: 313, 314 → C1, F1
    white_bishop_313: "C1"
    white_bishop_314: "F1"

    # White queen: 315 → D1
    white_queen_315: "D1"

    # White king: 316 → E1
    white_king_316: "E1"
